### ISSUE TITLE
cannot save otf when glyphs more than 65,000 ?

### ISSUE THREAD

**Issue by creatxrgithub** [opentypejs/opentype.js#413]
i remember that opentype font could have more than 65,000 glyphs in a font file.

"OpenType fonts may contain more than 65,000 glyphs," 

from: https://www.adobe.com/products/type/opentype.html

```
let font = new opentype.Font({
	familyName: familyName,
	styleName: 'Medium',
	unitsPerEm: unitsPerEm,
	ascender: ascender,
	descender: descender,
	glyphs: glyphs     //>65,000
	});
font.download();
```

node --max-old-space-size=8192 svg2otf.js  //console output: killed

**Comment by creatxrgithub** [comment]
other svg (less than 65,000 glyphs)

```
let font = new opentype.Font({
	familyName: familyName,
	styleName: 'Medium',
	unitsPerEm: unitsPerEm,
	ascender: ascender,
	descender: descender,
	glyphs: glyphs.slice(1,2)
	});

console.log(glyphs.slice(1,2));
fs.writeFileSync('glyphs.log',JSON.stringify(glyphs.slice(1,2)));

font.download();

```
console output :

app/node_modules/opentype.js/src/tables/sfnt.js:182
        var metrics = glyph.getMetrics();
                            ^

TypeError: glyph.getMetrics is not a function
    at Object.fontToSfntTable [as fontToTable] (/media/creatxr/DATAW/WORK/webapp/node_modules/opentype.js/src/tables/sfnt.js:182:29)
    at Font.toTables (/media/creatxr/DATAW/WORK/webapp/node_modules/opentype.js/src/font.js:423:17)
    at Font.toArrayBuffer (/media/creatxr/DATAW/WORK/webapp/node_modules/opentype.js/src/font.js:437:26)
    at Font.download (/media/creatxr/DATAW/WORK/webapp/node_modules/opentype.js/src/font.js:455:28)
    at Object.<anonymous> (/media/creatxr/DATAW/WORK/webapp/cli/svg2otf.js:71:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
