### ISSUE TITLE
How to Solve This Problem... 😭 Error: Unsupported OpenType signature <!DO

### ISSUE THREAD

**Issue by Sanghyun0505** [opentypejs/opentype.js#646]
## This error occurred to me, but I couldn't solve it. help me plzzz😭

```
Error: Unsupported OpenType signature <!DO
    at parseBuffer (opentype.js:209:1)
    at opentype.js:400:1
    at request.onload (opentype.js:70:1)
```
### Here is my code
```
import { CallbackType, OptionType } from "./type";
import opentype from "opentype.js";
import wrap from "word-wrap";

export const titleMaker = (options: OptionType, callback: CallbackType) => {
  const path = `../../fonts/${options.font || "GangwonEduPower"}.otf`;

  const wrapText = (text: string, width: number): string[] => {
    const wrappedText = wrap(text, { width }).split("\n");
    if (wrappedText.length > 3) return wrapText(text, width + 1);
    else return wrappedText;
  };

  const loadFont = async () => {
    try {
      const font = await opentype.load(path);
      const textArray = wrapText(options.title, 6);

      const maxWidth = font.getAdvanceWidth(
        textArray.reduce((a, b) => (a.length <= b.length ? b : a)),
        100
      );

      const result = textArray
        .map((item, index) => {
          const xPos = () => {
            if (options.alignLeft || false) return 0;
            else return (maxWidth - font.getAdvanceWidth(item, 100)) / 2;
          };

          const path = font.getPath(item, xPos(), 100 * (index + 1), 100);
          return path.toSVG(0);
        })
        .join("");

      const svg = [
        '<?xml version="1.0"?><svg',
        'xmlns="http://www.w3.org/2000/svg"',
        'xmlns:xlink="http://www.w3.org/1999/xlink"',
        `fill="${options.color || "white"}" width="${maxWidth}" height="${
          textArray.length * 110
        }"><g>${result}</g></svg>`,
      ].join(" ");

      callback(svg);
    } catch (err) {
      console.log(err);
    }
  };

  loadFont();
};
```

**Comment by Connum** [comment]
It looks like you're trying to load an html file (starting with `<!DOCTYPE`), so probably the path to the font file is wrong, resulting in an HTTP 404 status page. Check your browser's dev tools to check which URL it is trying to load, or use an absolute URL to the font file.

**Comment by Sanghyun0505** [comment]
thank you for the reply. However, I changed the absolute path code below, but the same error still occurs.
``` const path = `@doldory/titlemaker/fonts/${options.font || "GangwonEduPower"}.otf`; ```

And what I'm creating is a library on npm. Could you check the problem with my code one more time using the link below?
[https://www.npmjs.com/package/@doldory55/titlemaker](https://www.npmjs.com/package/@doldory55/titlemaker)

**Comment by ILOVEPIE** [comment]
We aren't here to fix problems with your code. Try debugging it yourself,
the issue you're having is that you have the wrong URL, try to see what URL
the project is requesting using the tools provided by the browser.Message
ID: ***@***.***>

>

**Comment by Connum** [comment]
Closing as not an issue with the library
