### ISSUE TITLE
`charToGlyph` throws error for missing glyph for fonts with default encoding

### ISSUE THREAD

**Issue by Balearica** [opentypejs/opentype.js#735]
## Current vs. Expected Behavior
The method `charToGlyph` converts a literal character to a glyph.  For the vast majority of fonts, using `charToGlyph` with a character that does not exist in the font results in the `.notdef` glyph being returned.  This behavior is expected and should happen for all fonts.  However, for fonts that use `DefaultEncoding`, an error is thrown.

## Cause
The `charToGlyph` function works by (1) calling `charToGlyphIndex` to get the glyph index for the character, and then (2) gets the glyph at that index.  This fails for fonts that use `DefaultEncoding`, as the `DefaultEncoding.charToGlyphIndex` function behaves differently from what is expected.  While `charToGlyphIndex` usually defaults to `0`, and the [type annotations](https://github.com/opentypejs/opentype.js/blob/e9c090ed801f74df2cedc2f1df937bd439070960/src/encoding.mjs#L226-L232) indicate it always returns a `number`, `charToGlyphIndex` defaults to `null` for fonts that use the default encoding.  When `charToGlyph` attempts to look up the glyph with index `null`, it throws an error.

https://github.com/opentypejs/opentype.js/blob/e9c090ed801f74df2cedc2f1df937bd439070960/src/encoding.mjs#L200-L214

https://github.com/opentypejs/opentype.js/blob/e9c090ed801f74df2cedc2f1df937bd439070960/src/font.mjs#L201-L210

## Possible Solution
The easiest fix would be to edit `charToGlyphIndex` to return `0` by default for fonts with default encoding, which would make the behavior match what happens for `CmapEncoding`.  In addition to fixing `charToGlyph`, this would have the following benefits.
1. It would standardize the behavior of `font.charToGlyphIndex`.
	1. It is unintuitive/surprising for the behavior of `font.charToGlyphIndex` to vary between fonts based on `encoding`, especially as `encoding` is an "under the hood" property users are not actively thinking about. 
2. It would make the existing types correct.
	1. The type annotations for `font.charToGlyphIndex` currently indicate it returns `number`, rather than `number|null`.

The only potential downside that I can think of is that this would produce unintuitive results in a case where a user creates their own font where the glyph with index `0` is not `.notdef`.  However, that seems more like user error than a legitimate use-case, and the existing OpenType.js [documentation](https://github.com/opentypejs/opentype.js?tab=readme-ov-file#craft-a-font) already states that adding `.notdef` is required.
## Steps to Reproduce (for bugs)
This can be demonstrated by creating a font using the snippet in the readme (reproduced below), which will have default encoding.

```js
// this .notdef glyph is required.
const notdefGlyph = new opentype.Glyph({
    name: '.notdef',
    advanceWidth: 650,
    path: new opentype.Path()
});

const aPath = new opentype.Path();
aPath.moveTo(100, 0);
aPath.lineTo(100, 700);
// more drawing instructions...
const aGlyph = new opentype.Glyph({
    name: 'A',
    unicode: 65,
    advanceWidth: 650,
    path: aPath
});

const font = new opentype.Font({
    familyName: 'OpenTypeSans',
    styleName: 'Medium',
    unitsPerEm: 1000,
    ascender: 800,
    descender: -200,
    glyphs: [notdefGlyph, aGlyph]});
```

Running `font.charToGlyph('😊')` with this font results in the following error:
```
glyphset.js:51 Uncaught TypeError: this.font._push is not a function
    at GlyphSet.get (glyphset.js:51:19)
    at Font.charToGlyph (font.js:142:29)
    at <anonymous>:1:7
```

## Context
My program intermingles `Font` objects created from font files (which use `CmapEncoding`) with `Font` objects created with OpenType.js (which use `DefaultEncoding`).  Errors started being thrown with certain combinations of user-inputs and fonts, and it was unclear why.

## Your Environment

* Version used: https://github.com/opentypejs/opentype.js/commit/e9c090ed801f74df2cedc2f1df937bd439070960
* Font used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Balearica** [comment]
Reviewing the code, I realized that on paper a similar issue also likely impacts `CffEncoding`.  However, this is likely not an issue as it does not appear that `CffEncoding` is actually used as the main encoding (`Font.encoding`) for any font.  The `cmap` encoding is always used over the `cff` encoding when it exists.

https://github.com/opentypejs/opentype.js/blob/e9c090ed801f74df2cedc2f1df937bd439070960/src/tables/cff.mjs#L1341-L1342

While this would seemingly indicate that the `CffEncoding` is sometimes used, `cmap` is a [required table](https://learn.microsoft.com/en-us/typography/opentype/spec/otff#font-tables) for OpenType/TrueType, and I confirmed that all fonts in the [test directory](https://github.com/opentypejs/opentype.js/tree/master/test/fonts) use `CmapEncoding`.  Therefore, it looks like `Font.encoding` will always be an instance of either `CmapEncoding` or `DefaultEncoding`.
